"""Add reminder field to tasks

Revision ID: 82be4326131e
Revises: eb1559c19283
Create Date: 2026-07-17 08:59:26.959323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82be4326131e'
down_revision = 'eb1559c19283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('reminder')

    # ### end Alembic commands ###
