"""Add milestones field to goals

Revision ID: eb1559c19283
Revises: f3c8e82f5e41
Create Date: 2026-07-17 08:14:11.369196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb1559c19283'
down_revision = 'f3c8e82f5e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('milestones', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_column('milestones')

    # ### end Alembic commands ###
