"""Update inspiration_images - remove NOT NULL from image_url

Revision ID: f875e0eeedfc
Revises: 82be4326131e
Create Date: 2026-07-17 09:38:54.252310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f875e0eeedfc'
down_revision = '82be4326131e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspiration_images', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspiration_images', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
